[Fixes]"payment_preference" field to Member model
nycmeshnet/meshdb pull request #407
Opened 2024-07-09 21:10 UTC by harsha-mangena

- refer https://github.com/nycmeshnet/meshdb/issues/394
- added attribute `payment_preference` on member
- added testcase

2024-07-11 03:05 UTC, WillNilges requested changes
Thanks for the contribution! I let the CI checks run, and it looks like you need to run our linters and makemigrations. You can find instructions [here](https://github.com/nycmeshnet/meshdb?tab=readme-ov-file#invokepy-commands).

I also left a suggestion for how to implement the payment preferences choices.

2024-07-11 03:05 UTC, WillNilges commented on src/meshapi/models/member.py
> +    payment_preference = models.CharField(choices=('cash', 'stripe', None), default=None)
Do you mind creating a `models.TextChoices` class for this (similar to what's used in [node.py](https://github.com/nycmeshnet/meshdb/blob/main/src/meshapi/models/node.py#L17-L20)?)

2024-07-13 18:25 UTC, WillNilges commented
Looks like you've got a syntax error causing the CI to fail. Can you fix that?

2024-11-09 23:06 UTC, Andrew-Dickinson commented
Closing this due to inactivity. Feel free to re-open if you want to continue working on this

2024-11-09 23:06 UTC, closed without merging