Resource request and limit
nycmeshnet/meshdb pull request #640
Opened 2024-10-11 03:41 UTC by james-otten

Set resource requests + limits based on current production usage as seen in el doggo.

Docs: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

2024-10-11 15:34 UTC, Andrew-Dickinson approved these changes

2024-10-12 04:58 UTC, WillNilges requested changes
Unless you have a very good reason, such as an app is startup-hungry, we should be pinning requests and limits. It makes things more predictable, simpler to debug, and there's no reason not to if we know we have the resources to spare.

Each of these pins should be done one at a time.

(Addendum, this is all based on my own experience. If you have a Datadog graph that proves me wrong, I'd like to see it.)

2024-10-12 04:58 UTC, WillNilges commented on infra/helm/meshdb/values.yaml
> +  resources:
We should definitely pin Postgres to a core. It deserves it.

2024-10-12 04:58 UTC, WillNilges commented on infra/helm/meshdb/values.yaml
> +      memory: 350Mi
Pin this guy to 512Mi. 200m is _probably_ fine as a request, as I think most of the CPU is on startup with the tracer.

2024-10-12 04:58 UTC, WillNilges commented on infra/helm/meshdb/values.yaml
> +      memory: 30Mi
This guy _definitely_ doesn't need more than 250mcore and like, 128Mi of RAM. If our web proxy is taking up more than that, we've either got wayyyy more users than we thought we did, or we have a performance problem.

2024-10-12 04:58 UTC, WillNilges commented on infra/helm/meshdb/values.yaml
> +      memory: 30Mi
Redis _really_ doesn't like not being pinned, especially as an in-memory cache. I'd say pin it to 256Mi and like..... 250mcore. If that doesn't work, bump it.

2024-10-12 04:58 UTC, WillNilges commented on infra/helm/meshdb/values.yaml
> +      memory: 250Mi
No fucking idea here. Can probably get away with pinning limit to the smaller request here tho.

2024-10-26 17:26 UTC, james-otten commented
> Can we do these one at a time? It'll be easier to debug if it's causing startup issues or something.
> 
> Also, I don't think we have the ability to gate our prod releases on whether or not dev is in a good state, which makes changes like these a little spooky 👻

Very spooky, has me saying AAAAHHHHHHH

1. https://github.com/nycmeshnet/meshdb/pull/655
2. https://github.com/nycmeshnet/meshdb/pull/656
3. https://github.com/nycmeshnet/meshdb/pull/657
4. https://github.com/nycmeshnet/meshdb/pull/658
5. https://github.com/nycmeshnet/meshdb/pull/659

2024-10-26 23:31 UTC, closed without merging

2024-10-26 23:31 UTC, james-otten commented
Several others